sonar.projectKey=fe-igualab
sonar.projectName=FE-IGUALAB
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=node_modules/**,dist/**,**/*.config.js,**/*.config.ts
sonar.sourceEncoding=UTF-8
