/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "#1f7a4d",
        "on-background": "#191c1c",
        "surface-container-low": "#f2f4f3",
        "secondary-fixed": "#84f6e6",
        "surface-tint": "#066c41",
        "on-secondary-container": "#007167",
        "on-primary-fixed-variant": "#00522f",
        "surface-container-high": "#e6e9e8",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f0",
        "background": "#f8faf9",
        "on-tertiary": "#ffffff",
        "primary": "#006038",
        "inverse-primary": "#82d8a3",
        "tertiary-fixed": "#ffdf9f",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#82d8a3",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#002110",
        "surface-variant": "#e1e3e2",
        "outline": "#6f7a71",
        "secondary-container": "#84f6e6",
        "on-primary-container": "#aeffca",
        "outline-variant": "#bec9bf",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#005049",
        "on-surface-variant": "#3f4941",
        "surface-container": "#eceeed",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffebc9",
        "surface-bright": "#f8faf9",
        "tertiary-fixed-dim": "#f8bd26",
        "on-tertiary-fixed": "#261a00",
        "surface": "#f8faf9",
        "surface-dim": "#d8dada",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#66d9ca",
        "tertiary": "#6b4f00",
        "inverse-surface": "#2e3131",
        "on-secondary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#5b4300",
        "surface-container-highest": "#e1e3e2",
        "primary-fixed": "#9ef5be",
        "on-surface": "#191c1c",
        "secondary": "#006a61",
        "tertiary-container": "#896600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        unit: "4px",
        gutter: "24px",
        "sidebar-width": "260px",
        "container-max": "1440px",
      },
      fontFamily: {
        body: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
